{{- define "temporal.password-env" -}}
{{- $root := index . 0 -}}
{{- $store := index . 1 -}}
valueFrom:
  secretKeyRef:
    name: {{ default (include "temporal.componentname" (list $root (printf "%s-store" $store.name))) $store.config.existingSecret }}
    key: {{ default "password" $store.config.secretKey }}
{{- end -}}
