{{- if and  $.Values.server.config.tls $.Values.certManager}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-selfsigned-ca-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-45"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-ca-certificate
  namespace: cert-manager
spec:
  secretName: {{ $.Release.Name }}-ca-secret
  isCA: true
  commonName: {{ $.Release.Name }}-ca
  issuerRef:
    name: {{ $.Release.Name }}-selfsigned-ca-issuer
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-selfsigned-issuer
spec:
  ca:
    secretName: {{ $.Release.Name }}-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-cluster-certificate
spec:
  dnsNames:
  - {{ include "temporal.componentname" (list . "frontend") }}
  - {{ include "temporal.componentname" (list . "frontend") }}.{{ $.Release.Namespace }}
{{- if $.Values.additionalDnsNames }}
{{- range $.Values.additionalDnsNames }}
  - {{ . }}
{{- end }}
{{- end }}
  subject:
    organizationalUnits:
    - "temporal:temporal-system:admin"
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-cluster-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-web-certificate
spec:
  dnsNames:
  - {{ $.Release.Name }}-web
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-web-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-admin-certificate
spec:
  dnsNames:
  - {{ $.Release.Name }}-admintools
  subject:
    organizationalUnits:
    - "temporal:temporal-system:admin"
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-admin-cert
---
{{- if not  $.Values.dev }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-provider-certificate
spec:
  dnsNames:
  - {{ $.Release.Name }}-provider
  subject:
    organizationalUnits:
    - "temporal:temporal-system:admin"
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-provider-cert
{{- end }}
{{- end }}
