{{- if and  $.Values.server.config.tls $.Values.certManager}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-selfsigned-ca-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-45"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-ca-certificate
  namespace: cert-manager
spec:
  secretName: {{ $.Release.Name }}-ca-secret
  isCA: true
  {{- with $.Values.rootCaCertLifetimeHours }}
  duration: {{ . }}h
  {{- end }}
  {{- with $.Values.rootCaCertRenewBeforeHours }}
  renewBefore: {{ . }}h
  {{- end }}
  commonName: {{ $.Release.Name }}-ca
  issuerRef:
    name: {{ $.Release.Name }}-selfsigned-ca-issuer
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-selfsigned-issuer
spec:
  ca:
    secretName: {{ $.Release.Name }}-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-cluster-certificate
spec:
  dnsNames:
  - {{ include "temporal.componentname" (list . "frontend") }}
  - {{ include "temporal.componentname" (list . "frontend") }}.{{ $.Release.Namespace }}
{{- if $.Values.additionalDnsNames }}
{{- range $.Values.additionalDnsNames }}
  - {{ . }}
{{- end }}
{{- end }}
  subject:
    organizationalUnits:
    - "temporal:temporal-system:admin"
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-cluster-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-web-certificate
spec:
  dnsNames:
  - {{ $.Release.Name }}-web
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-web-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-admin-certificate
spec:
  dnsNames:
  - {{ $.Release.Name }}-admintools
  subject:
    organizationalUnits:
    - "temporal:temporal-system:admin"
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-admin-cert
---
{{- if not  $.Values.dev }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-provider-certificate
spec:
  dnsNames:
  - {{ $.Release.Name }}-provider
  subject:
    organizationalUnits:
    - "temporal:temporal-system:admin"
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-provider-cert
{{- end }}
---
{{- if and $.Values.secretStore $.Values.secretStoreSecret }}
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: {{ $.Release.Name }}-pushsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-35"
spec:
  watch: true
  references:
  - patchesFrom:
      apiVersion: v1
      kind: Secret
      name: {{ $.Release.Name }}-ca-secret
      namespace: cert-manager
      fieldPath: metadata.resourceVersion
    toFieldPath: spec.data[0].match.remoteRef.property
  forProvider:
    manifest:
      apiVersion: external-secrets.io/v1alpha1
      kind: PushSecret
      metadata:
        name: pushsecret-{{ $.Release.Name }}
        namespace: cert-manager
      spec:
        updatePolicy: Replace
        refreshInterval: 1h
        secretStoreRefs:
          - name: {{ $.Values.secretStore }}
            kind: ClusterSecretStore
        selector:
          secret:
            name: {{ $.Release.Name }}-ca-secret
        data:
          - match:
              secretKey: tls.crt
              remoteRef:
                remoteKey: {{ $.Values.secretStoreSecret }}
  providerConfigRef:
    name: provider-kubernetes
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-root-ca-list
  namespace: cert-manager
spec:
  dataFrom:
    - extract:
        key: {{ $.Values.secretStoreSecret }}
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.secretStore }}
  target:
    name: {{ $.Release.Name }}-root-ca-list
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-trust-bundle
spec:
  sources:
  - secret:
      name: {{ $.Release.Name }}-ca-secret
      key: "tls.crt"
  - secret:
      name: {{ $.Release.Name }}-root-ca-list
      includeAllKeys: true
  target:
    secret:
      key: "trust-bundle.pem"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    {{- include "temporal.resourceLabels" (list . "" "") | nindent 4 }}
  name: {{ $.Release.Name }}-tctl-certificate
spec:
  dnsNames:
  - {{ $.Release.Name }}-tctl
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Release.Name }}-selfsigned-issuer
  secretName: {{ $.Release.Name }}-tctl-cert
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-tctl-{{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-35"
spec:
  updatePolicy: Replace
  refreshInterval: 1h
  secretStoreRefs:
    - name: {{ $.Values.secretStore }}
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $.Release.Name }}-tctl-cert
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: {{ $.Values.tctlSecretStoreSecret }}
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: {{ $.Values.tctlSecretStoreSecret }}
          property: tls.key
    - match:
        secretKey: ca.crt
        remoteRef:
          remoteKey: {{ $.Values.tctlSecretStoreSecret }}
          property: ca.crt
{{- end }}
{{- end }}
