{{- range $_, $store := (include "temporal.persistence.eachStore" $ | fromYaml) }}
  {{- if empty $store.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.persistence.secretName" (list $ $store) }}
  labels:
    {{- include "temporal.resourceLabels" (list $ "" "secret") | nindent 4 }}
  {{- with $.Values.server.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ default "" $store.config.password | b64enc | quote }}
---
  {{- end }}
{{- end }}
