apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "temporal.fullname" . }}-test-cluster-health"
  labels:
    {{- include "temporal.resourceLabels" (list $ "test" "") | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    {{- with .Values.test.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{ include "temporal.serviceAccount" . }}
  containers:
  - name: cluster-health
    image: "{{ .Values.admintools.image.repository }}:{{ .Values.admintools.image.tag }}"
    imagePullPolicy: {{ .Values.admintools.image.pullPolicy }}
    command: ["temporal", "operator", "cluster", "health"]
    env:
      - name: TEMPORAL_ADDRESS
        value: {{ include "temporal.fullname" . }}-frontend:{{ .Values.server.frontend.service.port }}
  restartPolicy: Never
