{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.componentname" (list $ "web") }}
  labels:
    {{- include "temporal.resourceLabels" (list $ "web" "") | nindent 4 }}
  {{- if .Values.web.service.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.web.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  {{- if eq .Values.web.service.type "LoadBalancer" }}
  {{- with .Values.web.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.web.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if hasKey .Values.web.service "nodePort" }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "temporal.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  {{- end }}
