apiVersion: v1
entries:
  temporal:
  - apiVersion: v2
    appVersion: 1.23.0
    created: "2024-03-28T17:08:28.330968+02:00"
    dependencies:
    - condition: cassandra.enabled
      name: cassandra
      repository: https://charts.helm.sh/incubator
      version: 0.14.3
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 15.1.3
    - condition: elasticsearch.enabled
      name: elasticsearch
      repository: https://helm.elastic.co
      version: 7.17.3
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 5.0.10
    description: Temporal is a distributed, scalable, durable, and highly available
      orchestration engine to execute asynchronous long-running business logic in
      a scalable and resilient way.
    digest: 1840425bc35269e30395c2faa76fbc43931b55bd9fb5f7d372a0b54953b9ece8
    home: https://temporal.io/
    keywords:
    - temporal
    - workflow
    - orchestration
    maintainers:
    - name: Temporal Technologies Inc.
      url: https://temporal.io/
    name: temporal
    sources:
    - https://github.com/temporalio/temporal
    type: application
    urls:
    - https://github.com/fairmoney/temporal-helm-charts/tree/fm-devops/charts/temporal/temporal-0.36.0.tgz
    version: 0.36.0
generated: "2024-03-28T17:08:28.321782+02:00"
